/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mb6iA2XNHEb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function MyPortfolio() {
  return (
    <div className="flex flex-col min-h-dvh bg-[#f8f9fa] text-[#333]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="size-6 text-[#6c5ce7]" />
          <span className="sr-only">John Doe</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-[#6c5ce7]"
            prefetch={false}
          >
            Home
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-[#6c5ce7]"
            prefetch={false}
          >
            Projects
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-[#6c5ce7]"
            prefetch={false}
          >
            About
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-[#6c5ce7]"
            prefetch={false}
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section id="hero" className="w-full pt-12 md:pt-24 lg:pt-32">
          <div className="container space-y-10 xl:space-y-16">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none text-[#6c5ce7]">
                  Prabhav Gautam
                </h1>
                <p className="mx-auto max-w-[700px] text-[#7b8c9e] md:text-xl">Full-Stack Developer | UI/UX Designer</p>
                <p className="mx-auto max-w-[700px] text-[#7b8c9e] md:text-xl">
                  I create beautiful and functional web applications.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="projects" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#6c5ce7]">Featured Projects</h2>
                <p className="max-w-[900px] text-[#7b8c9e] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Check out some of my latest web development projects.
                </p>
              </div>
            </div>
            <div className="mx-auto grid gap-8 sm:grid-cols-2 md:grid-cols-3 lg:max-w-5xl">
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Project 1"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                />
                <div className="absolute inset-0 flex flex-col items-start justify-end bg-gradient-to-t from-[rgba(108,92,231,0.7)] to-[rgba(108,92,231,0)] p-6 transition-all duration-300 group-hover:from-[rgba(108,92,231,0.4)]">
                  <h3 className="text-xl font-bold text-[#f8f9fa]">ChatAt</h3>
                  <p className="mt-2 text-sm text-[#f8f9fa]">Lorem ipsum</p>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Project 2"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                />
                <div className="absolute inset-0 flex flex-col items-start justify-end bg-gradient-to-t from-[rgba(108,92,231,0.7)] to-[rgba(108,92,231,0)] p-6 transition-all duration-300 group-hover:from-[rgba(108,92,231,0.4)]">
                  <h3 className="text-xl font-bold text-[#f8f9fa]">NoteFlip</h3>
                  <p className="mt-2 text-sm text-[#f8f9fa]">
                    A responsive e-commerce website built with Next.js and Stripe.
                  </p>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Project 3"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                />
                <div className="absolute inset-0 flex flex-col items-start justify-end bg-gradient-to-t from-[rgba(108,92,231,0.7)] to-[rgba(108,92,231,0)] p-6 transition-all duration-300 group-hover:from-[rgba(108,92,231,0.4)]">
                  <h3 className="text-xl font-bold text-[#f8f9fa]">Menu App</h3>
                  <p className="mt-2 text-sm text-[#f8f9fa]">A mobile-first blog built with Gatsby and Contentful.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="about" className="w-full py-12 md:py-24 lg:py-32 bg-[#f0f2f5]">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:grid-cols-2 lg:gap-10 lg:text-left">
            <div className="space-y-4">
              <img
                src="/placeholder.svg"
                width="300"
                height="300"
                alt="John Doe"
                className="mx-auto rounded-full w-40 h-40 object-cover"
              />
            </div>
            <div className="space-y-4">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-[#6c5ce7]">About Me</h2>
                <p className="max-w-[600px] text-[#7b8c9e] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  I'm a full-stack developer with a passion for creating beautiful and functional web applications. I
                  have experience working with a variety of technologies, including React, Node.js, and Tailwind CSS.
                </p>
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-bold text-[#6c5ce7]">Skills</h3>
                <ul className="grid grid-cols-2 gap-2 text-sm text-[#7b8c9e]">
                  <li>React</li>
                  <li>Node.js</li>
                  <li>Tailwind CSS</li>
                  <li>MongoDB</li>
                  <li>Git</li>
                  <li>Figma</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="w-full py-12 md:py-24 lg:py-32 bg-[#f0f2f5]">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-[#6c5ce7]">
                Get in Touch
              </h2>
              <p className="mx-auto max-w-[600px] text-[#7b8c9e] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Have a project in mind or just want to say hello? Fill out the form below and I'll get back to you as
                soon as possible.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="grid gap-4">
                <Input
                  type="text"
                  placeholder="Name"
                  className="w-full bg-[#f8f9fa] border-[#e4e7eb] focus:border-[#6c5ce7] focus:ring-[#6c5ce7]"
                />
                <Input
                  type="email"
                  placeholder="Email"
                  className="w-full bg-[#f8f9fa] border-[#e4e7eb] focus:border-[#6c5ce7] focus:ring-[#6c5ce7]"
                />
                <Textarea
                  placeholder="Message"
                  className="w-full bg-[#f8f9fa] border-[#e4e7eb] focus:border-[#6c5ce7] focus:ring-[#6c5ce7]"
                  rows={4}
                />
                <Button type="submit" className="w-full bg-[#6c5ce7] text-[#f8f9fa] hover:bg-[#5a4dba]">
                  Send Message
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-[#7b8c9e]">&copy; 2024 Prabhav Gautam. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4 text-[#6c5ce7]" prefetch={false}>
            Privacy
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4 text-[#6c5ce7]" prefetch={false}>
            Terms of Service
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function XIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}

export default MyPortfolio
